name: Build and Deploy Sphinx Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme

      - name: Build HTML docs
        run: make -C building_docs html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: building_docs/_build/html

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5  
